### ISSUE TITLE
wadxtract fails

### ISSUE THREAD

**Issue by Asharax** [makise-homura/wadtools#1]
I get the following error when trying to extract this wad file. Why would that be?

Analyzing Riven.wad.client:
Unknown header magic: 3035752.

**Comment by makise-homura** [comment]
Are you sure you're trying to unpack a correct wad file? (e.g., neither .pk3, nor .zip, nor any other format?)
The header magic seems to indicate it's anything but wad file.

If you're sure of it, may you please share the file for me to check it out?

**Comment by Asharax** [comment]
https://www.nexusmods.com/leagueoflegends/mods/22/

I believe it was this file, but I'm not playing league anymore. so I closed the issue

**Comment by makise-homura** [comment]
I checked it, and it looks like it's not of DOOM's WAD format (probably no more than a coincidence of file extension match). This tool is expected to work with WAD files used by DOOM and DOOM source ports, that can run games like DOOM/DOOM II, Heretic, Hexen, Strife, Chex Quest/Chex Quest 3, etc.

Thanks anyway for reporting, I've added some clarification to code and README.
